### ISSUE TITLE
Убрать функцию new_field из Field.cpp

### ISSUE THREAD

**Issue by stndart** [stndart/SFML-sandbox#25]

**Comment by Grandevul** [comment]
зачем?

**Comment by stndart** [comment]
Затем, что эта функция создаёт поле с конкретными параметрами. Единственное, что там должно быть - это загрузка из жсона. Или конструктор по умолчанию

**Comment by Grandevul** [comment]
фон пустой (или особенный) делать в конструкторе. А вообще для каждой карты должен быть свой фон (если мы захотим сделать прозрачные клетки).
setScale - ты про что?

**Comment by stndart** [comment]
Сделано через конфиги в .json в #56
