### ISSUE TITLE
изменить загрузку поля

### ISSUE THREAD

**Issue by Grandevul** [stndart/SFML-sandbox#26]
+загрзука размера поля
+load_field если он изменён

**Comment by stndart** [comment]
+default_start_position - стартовая позиция игрока по умолчанию. Загружать в переменные типа Vector2i default_player_pos, а в addPlayer добавить аргументы по умолчанию -1, и при -1 выставлять игрока по этим координатам

**Comment by Grandevul** [comment]
я забыл, что я хотел сказать словами "+load_field если он изменён". Ничего серьёзного в голову не пришло, всё остальное сделал. (Надо пулить ветки)
