### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by stndart** [stndart/SFML-sandbox#3]

**Comment by Grandevul** [comment]
сделал класс. осталось добавить на экран и проверить, что всё работает правильно

**Comment by Grandevul** [comment]
нужны ui с текстом

**Comment by stndart** [comment]
В связи с переработкой архитектуры интерфейса, осталось реализовать:
Отрисовку надписей
колбэки на "системные" вызовы, типа "закрыть окно" и "выйти из полноэкранного режима"

**Comment by stndart** [comment]
Сделано в ba467f4
