### ISSUE TITLE
Добавить обработку z-координаты

### ISSUE THREAD

**Issue by stndart** [stndart/SFML-sandbox#30]

**Comment by Grandevul** [comment]
1. **Позволительно** сделать это только для **разных** классов.
2. Также стоит заметить, что игрок может прятаться за большими объектами
3. Из-за пункта **2** стоит вынести вызовы отрисовки в **отдельный файл** и прописать эти вызовы **последовательно** друг за дружкой (желательно развернуть рекурсии). Добавить **комментарии**, где какой файл запускается, и **обобщения**, что именно рисуется(видимая связь).

_Обобщения_ - понятный текст(почти заголовки) для гуманитариев, которые играли в игру и видят код в первый раз. Если какие-то вызовы можно обобщить двумя словами, значит текст не очень понятный. ("Нарисовать игру" - не считается как обобщение).

**Comment by stndart** [comment]
Коммент Grandevul не читал, сортировку Cell_object по z-индексам добавил, чуть позже сделаю это без создания мапа каждый кадр.
